export interface Translations {
  welcome: {
    welcome: string;
    title: string;
    description: string;
    button: string;
  };
  about: {
    title: string;
    paragraph1: string;
    paragraph2: string;
    paragraph3: string;
  };
  about2: {
    title: string;
    paragraph1: string;
    paragraph2: string;
    paragraph3: string;
  };
  howTo: {
    title: string;
    description: string;
    cards: {
      signup: {
        title: string;
        description: string;
      };
      friends: {
        title: string;
        description: string;
      };
      traffic: {
        title: string;
        description: string;
      };
    };
  };
  stats: {
    title: string;
    description: string;
    users: string;
    visits: string;
    contribution: string;
    income: string;
  };
  cta: {
    title: string;
    description: string;
    signup: string;
    about: string;
  };
  footer: {
    copyright: string;
  };
  signup: {
    title: string;
    subtitle: string;
    form: {
      email: string;
      username: string;
      password: string;
      confirmPassword: string;
      firstName: string;
      lastName: string;
      submit: string;
      loginLink: string;
      loginText: string;
    };
    validation: {
      required: string;
      emailInvalid: string;
      passwordMismatch: string;
      passwordMinLength: string;
      usernameMinLength: string;
    };
    success: {
      title: string;
      message: string;
    };
    error: {
      title: string;
      userExists: string;
      serverError: string;
    };
  };
  forum: {
    title: string;
    subtitle: string;
    searchPlaceholder: string;
    tabs: {
      recent: string;
      hot: string;
      pinned: string;
    };
    categories: {
      title: string;
    };
    stats: {
      title: string;
      members: string;
      posts: string;
      online: string;
    };
    createPost: string;
  };
  auth: {
    loading: string;
    loginRequired: {
      title: string;
      message: string;
      signup: string;
      home: string;
    };
  };
}

export const translations: Record<string, Translations> = {
  en: {
    welcome: {
      welcome: "Welcome to the",
      title: "Ubuntu-Project",
      description:
        "Our idea is simple. We founded a company and we provide a Social Media Platform. If you sign up, you become a shareholder in that company, meaning any profit generated by our platform, will be divided between <strong>all</strong> of us.",
      button: "Sounds interesting?",
    },
    about: {
      title: "Here's the plan...",
      paragraph1:
        "Data is a massive ressource in the modern web. It is collected where ever we go and the companies owning the platforms we use, generate billions in revenue selling this data to various customers. Our business model isn't only about profits — it's about <strong>ownership</strong>. Ownership of the data and spaces we build and use together.",
      paragraph2:
        'So what if we could build a platform hosting millions of users, that generates vast amounts of data, but we collectively own everything at the same time? Examples like the <a href="https://en.wikipedia.org/wiki/GameStop_short_squeeze" style="color: inherit;" target="_blank" rel="noopener noreferrer">GameStop Short-Squeeze</a> demonstrated impressively, how much impact we as consumers really have, as long as we bundle our efforts. We have come to the overdue conclusion, that in order to fundamentally succeed, we will need each other.',
      paragraph3:
        "First, we want to build a community. A big one. We've started by creating a Twitter-Like-Forum that allows us to exchange ideas, collaborate  and vote on critical decisions. Swing by if you want to know a little more about our thoughts and ideas, maybe even share your own?",
    },
    about2: {
      title: "Something important to us:",
      paragraph1:
        "We are an <strong>economical</strong> community, not a political, religious or other. We welcome everyone, who is willing to respect others for their personal preferences and convictions, as long as these are compatible with the aforementioned fundamental values.",
      paragraph2:
        "Also it is <strong>not</strong> our intention to design a system that ties contribution to personal financial reward. Though we are open to discuss a minimal financial hierarchical system, we believe that lasting prosperity can only be achieved at the <strong>collective level</strong> — and we are committed to preserving that principle.",
      paragraph3:
        "That said, we are not free of hierarchy. For now we — the founders — act as administrators of the platform, servers, and repositories, serving as the company's functional leadership, in order to ensure the preservation of our values and goals. In the long run, we aim to establish a more distributed model — electing spokespersons by area of expertise and making key decisions collectively.",
    },
    howTo: {
      title: "What can you do?",
      description:
        "Don't worry, we are not asking you to work for us. Actually we see it quite the other way around. But no matter if you actively contribute or not, there is still something you can do for us. By following at least one of these <strong>3-Step-Plan</strong> for us:",
      cards: {
        signup: {
          title: "1. Sign up",
          description:
            "Our first goal is to achieve a certain amount of registrated users. Our strength will come from numbers. And our resource will be ourselves.",
        },
        friends: {
          title: "2. Tell your Friends",
          description:
            "Tell people about us. There is literally no downside to signing up, there is no mandatory tasks anyone must do. But this is your company now too.",
        },
        traffic: {
          title: "3. Generate traffic",
          description:
            "One daily visit would already help. You could save us as your browser's homepage. If we have traffic, we have attention and if we have attention we will be able to decide what to do with it.",
        },
      },
    },
    stats: {
      title: "How it's going so far?",
      description:
        "We have launched in October 2025 and these are our current numbers.",
      users: "Registered Users",
      visits: "Daily Visits",
      contribution: "User contribution",
      income: "Income generated",
    },
    cta: {
      title: "Care to join?",
      description:
        "We will not ask any sensitive information of you. Email, Password and a funky Username should do the trick for now.",
      signup: "Sign up",
      about: "About Us",
    },
    footer: {
      copyright: "© 2025 siefke1. All rights reserved. Built with ❤️",
    },
    signup: {
      title: "Join the Ubuntu-Project",
      subtitle: "Yes, we like old-school registration forms.",
      form: {
        email: "Email",
        username: "Username",
        password: "Password",
        confirmPassword: "Confirm Password",
        firstName: "First Name",
        lastName: "Last Name",
        submit: "Sign Up",
        loginLink: "Already have an account?",
        loginText: "Sign in here",
      },
      validation: {
        required: "This field is required",
        emailInvalid: "Please enter a valid email address",
        passwordMismatch: "Passwords do not match",
        passwordMinLength: "Password must be at least 6 characters",
        usernameMinLength: "Username must be at least 3 characters",
      },
      success: {
        title: "Welcome aboard!",
        message:
          "Your account has been created successfully. You are now an equal shareholder in our collective venture.",
      },
      error: {
        title: "Sign up failed",
        userExists: "A user with this email or username already exists",
        serverError: "Something went wrong. Please try again.",
      },
    },
    forum: {
      title: "Ubuntu-Project Forum",
      subtitle: "Connect, Learn, and Share with the Ubuntu Community",
      searchPlaceholder: "Search discussions...",
      tabs: {
        recent: "Recent",
        hot: "Hot",
        pinned: "Pinned",
      },
      categories: {
        title: "Categories",
      },
      stats: {
        title: "Community Stats",
        members: "Members",
        posts: "Posts",
        online: "Online Now",
      },
      createPost: "Create New Post",
    },
    auth: {
      loading: "Loading...",
      loginRequired: {
        title: "Login Required",
        message: "You need to be logged in to access this page.",
        signup: "Sign Up",
        home: "Log In",
      },
    },
  },
  de: {
    welcome: {
      welcome: "Willkommen beim",
      title: "Ubuntu-Projekt",
      description:
        "Unsere Idee ist simpel. Wir haben ein Unternehmen gegründet und stellen eine Social Media Plattform zur Verfügung. Wenn Du dich anmeldest, wirst du ein Anteilseigner unseres Unternehmes. Das bedeutet jeglicher Umsatz den die Plattform generiert, wird unter <strong>Allen</strong> aufgeteilt.",
      button: "Neugierig geworden?",
    },
    about: {
      title: "Hier ist der Plan...",
      paragraph1:
        "Daten sind heute eine Ressource mit hoher Nachfrage. Sie werden von uns ermittelt wohin wir auch gehen und die Besitzer der Plattformen die wir benutzen, streichen Milliardengewinne ein, mit dem Verkauf dieser Daten. Unser Geschätsmodell verspricht keine schnellen Gewinne, sondern <strong>Beteiligung</strong>. Beteiligung an den Räumen in denen wir uns aufhalten und den Daten die darin generiert werden.",
      paragraph2:
        'Was, wenn wir in der Lage sind, eine Plattform aufzubauen, die Millionen von Nutzern beheimatet, die große Mengen an Daten generiert, die wir selbstbestimmt verwalten und verkaufen können? Beispiele wie die <a href="https://en.wikipedia.org/wiki/GameStop_short_squeeze" style="color: inherit;" target="_blank" rel="noopener noreferrer">GameStop Short-Squeeze</a> haben eindrucksvoll demonstriert, wie viel mehr Einfluss wir als Verbraucher wirklich haben. Wir sind zu dem überfälligen Entschluss gekommen, dass wir einander brauchen werden, um langfristig erfolgreich zu sein.',
      paragraph3:
        "Also wollen wir eine Community bauen. Eine ziemlich große. Wir haben mit der Erstellung eines Twitter-Like-Forums begonnen, das es uns ermöglicht, Ideen auszutauschen, zusammenzuarbeiten und über wichtige Entscheidungen abzustimmen. Schau dort vorbei wenn du ein bisschen mehr über unsere Pläne und Ideen erfahren möchtest oder Dich vielleicht sogar einbringen möchtest?",
    },
    about2: {
      title: "Etwas das uns wichtig ist:",
      paragraph1:
        "Wir sind in erster Linie eine <strong>ökonomische</strong> Gemeinschaft, keine politische, religiöse oder andere. Bei uns sind Menschen willkommen, die in der Lage sind Andere für Ihre persönlichen Einstellungen und Überzeugungen zu respektieren, solange diese im Einklang mit eben jenen Grundsätzen stehen.",
      paragraph2:
        "Außerdem ist es <strong>nicht</strong> unsere Absicht, ein System zu entwerfen, das Leistung mit persönlicher finanzieller Belohnung verknüpft. Wir sind offen ein minimales Stufensystem zu diskutieren, glauben grundsätzlich aber dass kontinuierlicher Wohlstand nur auf <strong>kollektiver Ebene</strong> erreicht werden kann — und wir sind entschlossen, dieses Prinzip zu bewahren.",
      paragraph3:
        "Wir sind aber auch nicht ganz frei von Hierarchien. Vorerst fungieren wir — die GründerInnen — als Administratoren der Plattform, Server und Code-Base und dienen als funktionale Führung des Unternehmens - maßgeblich um den Erhalt unserer Werte und Ziele zu garantieren. Langfristig streben wir ein verteilteres Modell an — die Wahl von Sprecherinnen und Sprechern nach Fachgebiet und kollektive Entscheidungsfindung.",
    },
    howTo: {
      title: "Was kannst du tun?",
      description:
        "Keine Angst, wir erwarten nicht von Dir, dass Du für uns arbeitest. Tatsächlich sehen wir die Sache genau anders herum. Aber auch wenn Du Dich vielleicht nicht aktiv beteiligen möchtest, gibt es trotzdem etwas dass Du für uns tun kannst. Für den Anfang haben wir uns einen einfachen <strong>3-Schritte-Plan</strong> überlegt:",
      cards: {
        signup: {
          title: "1. Melde Dich an",
          description:
            "Unser erstes Ziel ist es, eine große Anzahl registrierter Benutzer zu erreichen. Je mehr wir sind, desto besser, denn unsere Ressource werden wir selbst sein.",
        },
        friends: {
          title: "2. Erzähle es weiter",
          description:
            "Erzähl den Leuten von uns. Schlage Freunden vor sich anzumelden. Schließlich ist es jetzt auch dein Unternehmen.",
        },
        traffic: {
          title: "3. Traffic generieren",
          description:
            "Ein täglicher Besuch würde bereits helfen. Du könntest uns als deine Browser-Startseite speichern. Wenn wir Traffic haben, haben wir Aufmerksamkeit und wenn wir Aufmerksamkeit haben, können wir entscheiden, was wir damit machen.",
        },
      },
    },
    stats: {
      title: "Wie läuft es bisher?",
      description:
        "Wir haben im Oktober 2025 gestartet und das sind unsere aktuellen Zahlen.",
      users: "Registrierte Benutzer",
      visits: "Besuche Heute",
      contribution: "Benutzerbeitrag",
      income: "Generiertes Einkommen",
    },
    cta: {
      title: "Lust mitzumachen?",
      description:
        "Wir werden dich nach keinerlei vertraulichen Informationen fragen. E-Mail, Passwort und ein lustiger Benutzername sollten reichen für den Anfang.",
      signup: "Anmelden",
      about: "Über uns",
    },
    footer: {
      copyright: "©2025 siefke1. All rights reserved. Built with ❤️",
    },
    signup: {
      title: "Dem Ubuntu-Projekt beitreten",
      subtitle: "Ja, wir mögen old-school Anmelde-Formulare.",
      form: {
        email: "E-Mail",
        username: "Benutzername",
        password: "Passwort",
        confirmPassword: "Passwort bestätigen",
        firstName: "Vorname",
        lastName: "Nachname",
        submit: "Anmelden",
        loginLink: "Bereits ein Konto?",
        loginText: "Hier anmelden",
      },
      validation: {
        required: "Dieses Feld ist erforderlich",
        emailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
        passwordMismatch: "Passwörter stimmen nicht überein",
        passwordMinLength: "Passwort muss mindestens 6 Zeichen lang sein",
        usernameMinLength: "Benutzername muss mindestens 3 Zeichen lang sein",
      },
      success: {
        title: "Willkommen an Bord!",
        message:
          "Ihr Konto wurde erfolgreich erstellt. Sie sind jetzt ein gleichberechtigter Aktionär in unserem kollektiven Unternehmen.",
      },
      error: {
        title: "Anmeldung fehlgeschlagen",
        userExists:
          "Ein Benutzer mit dieser E-Mail oder diesem Benutzernamen existiert bereits",
        serverError:
          "Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.",
      },
    },
    forum: {
      title: "Ubuntu-Project Forum",
      subtitle: "Verbinden, Lernen und Teilen mit der Ubuntu Community",
      searchPlaceholder: "Diskussionen durchsuchen...",
      tabs: {
        recent: "Neueste",
        hot: "Beliebt",
        pinned: "Angepinnt",
      },
      categories: {
        title: "Kategorien",
      },
      stats: {
        title: "Community Statistiken",
        members: "Mitglieder",
        posts: "Beiträge",
        online: "Jetzt online",
      },
      createPost: "Neuen Beitrag erstellen",
    },
    auth: {
      loading: "Laden...",
      loginRequired: {
        title: "Anmeldung erforderlich",
        message: "Sie müssen angemeldet sein, um auf diese Seite zuzugreifen.",
        signup: "Registrieren",
        home: "Anmelden",
      },
    },
  },
};

export const getTranslations = (language: string = "en"): Translations => {
  return translations[language] || translations.en;
};
