export interface Translations {
  welcome: {
    welcome: string;
    title: string;
    description: string;
    button: string;
  };
  about: {
    title: string;
    paragraph1: string;
    // paragraph2Title: string;
    // paragraph2: string;
    // paragraph3Title: string;
    // paragraph3: string;
  };
  about2: {
    title: string;
    paragraph1: string;
    paragraph2: string;
    paragraph3: string;
  };
  socialMediaStats: {
    title: string;
    description: string;
    platforms: {
      meta: {
        name: string;
        revenue: string;
        dataVolume: string;
        description: string;
      };
      youtube: {
        name: string;
        revenue: string;
        dataVolume: string;
        description: string;
      };
      tiktok: {
        name: string;
        revenue: string;
        dataVolume: string;
        description: string;
      };
    };
    totalRevenue: string;
    totalDataVolume: string;
    note: string;
  };
  canItWork: {
    title: string;
    paragraph1: string;
    paragraph2: string;
  };
  imagine: {
    title: string;
    paragraph: string;
  };
  howTo: {
    title: string;
    description: string;
    cards: {
      signup: {
        title: string;
        description: string;
      };
      friends: {
        title: string;
        description: string;
      };
      traffic: {
        title: string;
        description: string;
      };
    };
  };
  stats: {
    title: string;
    description: string;
    users: string;
    visits: string;
    contribution: string;
    income: string;
  };
  cta: {
    title: string;
    description: string;
    signup: string;
    about: string;
  };
  footer: {
    copyright: string;
  };
  signup: {
    title: string;
    subtitle: string;
    form: {
      email: string;
      username: string;
      password: string;
      confirmPassword: string;
      firstName: string;
      lastName: string;
      submit: string;
      loginLink: string;
      loginText: string;
    };
    validation: {
      required: string;
      emailInvalid: string;
      passwordMismatch: string;
      passwordMinLength: string;
      usernameMinLength: string;
    };
    success: {
      title: string;
      message: string;
    };
    error: {
      title: string;
      userExists: string;
      serverError: string;
    };
  };
  forum: {
    title: string;
    subtitle: string;
    searchPlaceholder: string;
    tabs: {
      recent: string;
      hot: string;
      pinned: string;
    };
    categories: {
      title: string;
    };
    stats: {
      title: string;
      members: string;
      posts: string;
      online: string;
    };
    createPost: string;
  };
  auth: {
    loading: string;
    loginRequired: {
      title: string;
      message: string;
      signup: string;
      home: string;
    };
  };
}

export const translations: Record<string, Translations> = {
  en: {
    welcome: {
      welcome: "Welcome to the",
      title: "Ubuntu-Project",
      description:
        "Our idea is simple. We founded a Tech Company and our product is a Social Media Platform. So what's the deal? If you sign up on our platform, you will become a silent shareholder in our company, meaning any profit generated by the platform, will be divided between <strong>all</strong> of it's users.",
      button: "Sounds interesting?",
    },
    about: {
      title: "Here's the plan...",
      paragraph1:
        "How do Tech Companies make billions of dollars, while running 'free' products? The answer is your data and your attention. Advertisers, Marketing Firms and Data Brokers are willing to pay big amounts of money to the owners of that attention, on order to get access to it. Our question is, if it is ultimately our own resources that are desired, why should we not be the ones to profit from it? Our business model isn't about fast revenue  — it's about <strong>ownership</strong>. Ownership of the data and spaces we build and use together.",
    },
    about2: {
      title: "Something important to us:",
      paragraph1:
        "We are an <strong>economical</strong> community, not a political, religious or other. We welcome everyone, who is willing to respect others for their personal preferences and convictions, as long as these are compatible with the aforementioned fundamental values.",
      paragraph2:
        "Also it is <strong>not</strong> our intention to design a system that ties contribution to personal financial reward. Though we are open to discuss a minimal financial hierarchical system, we believe that lasting prosperity can only be achieved at the <strong>collective level</strong> — and we are committed to preserving that principle.",
      paragraph3:
        "For now we — the founders — act as administrators of the platform, servers, and repositories, serving as the company's functional leadership, in order to ensure the preservation of our values and goals. In the long run, we aim to establish a more distributed model — electing spokespersons by area of expertise and voting democratically on all important decisions.",
    },
    socialMediaStats: {
      title: "The Scale of Social Media",
      description:
        "Understanding the massive data generation and revenue from the biggest social media platforms",
      platforms: {
        meta: {
          name: "Meta (Facebook & Instagram)",
          revenue: "$164.5B",
          dataVolume: "4+ PB/day",
          description:
            "Dominates social media advertising with comprehensive user profiling",
        },
        youtube: {
          name: "YouTube (Alphabet)",
          revenue: "$36.1B",
          dataVolume: "500+ TB/day",
          description:
            "Leading video platform with extensive content and user data collection",
        },
        tiktok: {
          name: "TikTok",
          revenue: "$18B",
          dataVolume: "1+ PB/day",
          description:
            "Fastest growing platform with advanced AI-driven content analysis",
        },
      },
      totalRevenue: "$218.6B",
      totalDataVolume: "5.5+ PB/day",
      note: "Data estimates based on 2024 research. Actual figures may vary.",
    },
    canItWork: {
      title: "Can it work?",
      paragraph1:
        'In early 2021 several hedge funds heavily shorted the Stock (that means betting that its price would fall) of an old-school-gaming company, called GameStop. Originating from a Sub-Reddit, thousands of small investors coordinated to buy GameStop stock, driving up its price and saving the company, while forcing major hedge funds into massive losses. Examples like the <a href="https://en.wikipedia.org/wiki/GameStop_short_squeeze" style="color: inherit;" target="_blank" rel="noopener noreferrer">GameStop Short-Squeeze</a> demonstrated impressively, how much power we as consumers really have to change the status quo, as long as we bundle our efforts. A status quo where the many bear the cost so that the few may reap the rewards. We have come to the overdue conclusion, that in order to fundamentally succeed, we will need <strong>each other</strong>.',
      paragraph2:
        "First, we need to build a community. A big one. We've started by creating a Twitter-Like-Forum that allows us to exchange ideas, collaborate and vote on critical decisions. Swing by if you want to know a little more about our thoughts and ideas, maybe even share your own?",
    },
    imagine: {
      title: "Real talk...",
      paragraph:
        "Now let's be honest here. Meta's 164 Billion Profit divided by its 3.5 Billion active users, equals about 47$ of revenue per user anually. So this is not about getting rich. This is about having agency and resisting an ever growing trend of monetization of our time and data, the paralysis of the paywall and the illusion of choice. <br /> <br /> We've started by creating a Twitter-Like-Forum that allows us to exchange ideas, collaborate and vote on critical decisions. We believe that together, we could build something special.",
    },
    howTo: {
      title: "What can you do?",
      description:
        "Don't worry, we are not asking you to work for us. Actually we see it quite the other way around. But no matter if you actively contribute or not, there is still something you could do for us. By completing at least one of our <strong>3-Step-Plan</strong>:",
      cards: {
        signup: {
          title: "1. Sign up",
          description:
            "Our first goal is to achieve a certain amount of registered users. Our strength will come from numbers. And our resource will be ourselves.",
        },
        friends: {
          title: "2. Tell your Friends",
          description:
            "Tell people about us. There is literally no downside to signing up, there is no mandatory tasks, hidden costs or newsletter spam. But this is your company now too.",
        },
        traffic: {
          title: "3. Generate traffic",
          description:
            "One daily visit would already help. You could save us as your browser's homepage. If we have traffic, we have attention and if we have attention we will be able to decide what to do with it.",
        },
      },
    },
    stats: {
      title: "How it's going so far?",
      description:
        "We launched in October 2025 and our first goal is to reach 1 Million Registered Users. These are our current numbers.",
      users: "Registered Users",
      visits: "Daily Visits",
      contribution: "User contribution",
      income: "Profit generated",
    },
    cta: {
      title: "Care to join?",
      description:
        "We will not ask any sensitive information of you. Email, Password and a funky Username should do the trick for now.",
      signup: "Sign up",
      about: "About Us",
    },
    footer: {
      copyright: "© 2025 siefke1. All rights reserved. Built with ❤️",
    },
    signup: {
      title: "Join the Ubuntu-Project",
      subtitle: "We really do like old-school registration forms.",
      form: {
        email: "Email",
        username: "Username",
        password: "Password",
        confirmPassword: "Confirm Password",
        firstName: "First Name",
        lastName: "Last Name",
        submit: "Sign Up",
        loginLink: "Already have an account?",
        loginText: "Sign in here",
      },
      validation: {
        required: "This field is required",
        emailInvalid: "Please enter a valid email address",
        passwordMismatch: "Passwords do not match",
        passwordMinLength: "Password must be at least 6 characters",
        usernameMinLength: "Username must be at least 3 characters",
      },
      success: {
        title: "Welcome aboard!",
        message:
          "Your account has been created successfully. You are now an equal shareholder in our collective venture.",
      },
      error: {
        title: "Sign up failed",
        userExists: "A user with this email or username already exists",
        serverError: "Something went wrong. Please try again.",
      },
    },
    forum: {
      title: "Ubuntu-Project Forum",
      subtitle: "Connect, Learn, and Share with the Ubuntu Community",
      searchPlaceholder: "Search discussions...",
      tabs: {
        recent: "Recent",
        hot: "Hot",
        pinned: "Pinned",
      },
      categories: {
        title: "Categories",
      },
      stats: {
        title: "Community Stats",
        members: "Members",
        posts: "Posts",
        online: "Online Now",
      },
      createPost: "Create New Post",
    },
    auth: {
      loading: "Loading...",
      loginRequired: {
        title: "Login Required",
        message: "You need to be logged in to access this page.",
        signup: "Sign Up",
        home: "Log In",
      },
    },
  },
  de: {
    welcome: {
      welcome: "Willkommen beim",
      title: "Ubuntu-Projekt",
      description:
        "Unsere Idee ist simpel. <br />Wir haben ein Tech Unternehmen gegründet und unser Produkt ist eine Social Media Plattform. Also wo ist der Witz? Wenn Du dich bei uns anmeldest, wirst du stiller Teilhaber unseres Unternehmes. Das bedeutet jeglicher Gewinn, den die Plattform generiert, wird unter <strong>allen</strong> BenutzerInnen aufgeteilt.",
      button: "Neugierig geworden?",
    },
    about: {
      title: "Hier ist der Plan...",
      paragraph1:
        "Hast Du dich schon mal gefragt wie Tech Firmen Milliardengewinne machen, während sie ein 'kostenloses' Produkt monetarisieren? Die Antwort ist Daten und Aufmerksamkeit. Marketing-Firmen, Medienkonzerne und Data-Brokers sind bereit denen die diese Aufmerksamkeit beitzen, viel Geld zu zahlen. Wenn es also im Endeffekt unsere eigenen Resourcen sind um die es geht, warum sollten wir nicht selbst davon profitieren? Unser Fokus liegt nicht auf schnellen Gewinnen, sondern auf <strong>Beteiligung</strong>. Und damit auch Kontrolle über die Algorithmen die unsere Inhalte bestimmen.",
    },
    about2: {
      title: "Etwas das uns wichtig ist:",
      paragraph1:
        "Wir sind eine <strong>ökonomische</strong> Gemeinschaft, keine politische, religiöse oder sonstige. Alle sind willkommen, die in der Lage sind Andere für Ihre persönlichen Einstellungen und Überzeugungen zu respektieren, solange diese im Einklang mit eben jenen Grundsätzen stehen.",
      paragraph2:
        "Außerdem ist es <strong>nicht</strong> unsere Absicht, ein System zu entwerfen, das Leistung mit persönlicher finanzieller Belohnung verknüpft. Wir sind offen ein minimales Stufensystem zu diskutieren, glauben aber grundsätzlich, dass kontinuierlicher Wohlstand nur auf <strong>kollektiver Ebene</strong> erreicht werden kann — und sind entschlossen, dieses Prinzip zu bewahren.",
      paragraph3:
        "Vorerst fungieren wir — die GründerInnen — als Administratoren der Plattform, Server und Code-Base und dienen als funktionale Führung des Unternehmens - maßgeblich um den Erhalt unserer Werte und Ziele zu garantieren. Langfristig streben wir ein verteilteres Modell an — die Wahl von Sprecherinnen und Sprechern nach Fachgebiet und kollektive Entscheidungsfindung.",
    },
    socialMediaStats: {
      title: "Das Ausmaß der Social Media",
      description:
        "Verstehen der massiven Datengenerierung und Einnahmen der größten Social Media Plattformen",
      platforms: {
        meta: {
          name: "Meta (Facebook & Instagram)",
          revenue: "164,5 Mrd. $",
          dataVolume: "4+ PB/Tag",
          description: "Größtes Social Media Unternehmen",
        },
        youtube: {
          name: "YouTube (Alphabet)",
          revenue: "36,1 Mrd. $",
          dataVolume: "500+ TB/Tag",
          description: "Führende Video-Plattform",
        },
        tiktok: {
          name: "TikTok",
          revenue: "18 Mrd. $",
          dataVolume: "1+ PB/Tag",
          description: "Führende Social Media Plattform für Menschen unter 30",
        },
      },
      totalRevenue: "218,6 Mrd. $",
      totalDataVolume: "5,5+ PB/Tag",
      note: "Datenschätzungen basierend auf 2024 Forschung. Tatsächliche Zahlen können variieren.",
    },
    canItWork: {
      title: "Kann es funktionieren?",
      paragraph1:
        'Im Frühjahr 2021 wetteten diverse Hedgefonds massiv gegen die Aktie eines altmodischen Videospielunternehmens namens GameStop. In einem Sub-Reddit beschloss eine kleine Community dem entgegenzuwirken, organisierten sich zu tausenden und kauften GameStock Aktien, was den Kurs in die Höhe trieb und die Firma vor dem Ruin rettete, nicht ohne besagten Hedgefonds große Verluste einzubringen. Beispiele wie der <a href="https://en.wikipedia.org/wiki/GameStop_short_squeeze" style="color: inherit;" target="_blank" rel="noopener noreferrer">GameStop Short-Squeeze</a> haben eindrucksvoll demonstriert, dass wir als Verbraucher, am Status Quo durchaus etwas verändern können. Ein Status quo, der die Arbeit vieler braucht, um den absurden Wohlstand weniger zu sichern. Wir sind zu dem überfälligen Entschluss gekommen, dass wir <strong>einander</strong> brauchen werden, um langfristig erfolgreich zu sein.',
      paragraph2:
        "Wir wollen eine Gemeinschaft gründen. Eine ziemlich große. Wir haben mit der Erstellung eines Twitter-Like-Forums begonnen, das uns ermöglicht, Ideen auszutauschen, zusammenzuarbeiten und über Entscheidungen abzustimmen. Schau vorbei wenn du ein bisschen mehr über unsere Arbeit und Pläne erfahren möchtest. Oder viellecht hast du selbst Vorschläge?",
    },
    imagine: {
      title: "Butter bei die Fische...",
      paragraph:
        "Meta's 164.5 Milliardenumsatz geteilt durch ihre 3.5 Milliarden aktiven Benutzer, ergibt etwa 47$ pro Account. Es geht uns nicht um's Geld, es geht um Selbstbestimmung und Widerstand gegen einen stetig voranschreitenden Trend von der Monetisierung unserer Zeit und Daten, der Paralyse der Paywall und der Illusion dass wir in diesen Netzwerken nicht völlig austauschbar sind. <br /> <br /> Wir haben mit der Erstellung einer Art Mischung aus Twitter und Reddit begonnen, das uns ermöglicht, Ideen auszutauschen, miteinander zu kollaborieren und über Entscheidungen abzustimmen. Wir sind fest davon überzeugt, dass wir zusammen etwas beispielloses bauen können.",
    },
    howTo: {
      title: "Was kannst du tun?",
      description:
        "Keine Angst, wir erwarten nicht, dass Du für uns arbeitest. Tatsächlich sehen wir die Sache genau anders herum. Aber auch wenn Du Dich vielleicht nicht aktiv beteiligst, gibt es trotzdem etwas dass Du für uns tun kannst, dafür haben wir uns einen einfachen <strong>3-Schritte-Plan</strong> überlegt:",
      cards: {
        signup: {
          title: "1. Melde Dich an",
          description:
            "Unser erstes Ziel ist es, eine große Anzahl registrierter Benutzer zu erreichen. Je mehr wir sind, desto besser, denn unsere Ressource werden wir selbst sein.",
        },
        friends: {
          title: "2. Erzähle es weiter",
          description:
            "Rühr die Werbetrommel! Es gibt keine Pflichten, versteckten Kosten oder Newsletter Spam nach der Anmeldung. Und schließlich ist es jetzt auch Deine Firma.",
        },
        traffic: {
          title: "3. Traffic generieren",
          description:
            "Ein täglicher Besuch würde bereits helfen. Du könntest uns als deine Browser-Startseite speichern. Wenn wir Traffic haben, haben wir Aufmerksamkeit und wenn wir Aufmerksamkeit haben, können wir entscheiden, was wir damit machen.",
        },
      },
    },
    stats: {
      title: "Wie läuft es bisher?",
      description:
        "Wir haben im Oktober 2025 gestartet und unser erstes Ziel ist es, eine Millionen registrierte Benutzer zu erreichen. Dies sind unsere aktuellen Zahlen.",
      users: "Registrierte Benutzer",
      visits: "Besuche Heute",
      contribution: "Benutzerbeitrag",
      income: "Generiertes Einkommen",
    },
    cta: {
      title: "Lust mitzumachen?",
      description:
        "Wir werden dich nach keinerlei vertraulichen Informationen fragen. E-Mail, Passwort und ein lustiger Benutzername sollten reichen für den Anfang.",
      signup: "Anmelden",
      about: "Über uns",
    },
    footer: {
      copyright: "©2025 siefke1. All rights reserved. Built with ❤️",
    },
    signup: {
      title: "Dem Ubuntu-Projekt beitreten",
      subtitle: "Hotmail-Adressen sind Tabu für Ü-30-Jährige.",
      form: {
        email: "E-Mail",
        username: "Benutzername",
        password: "Passwort",
        confirmPassword: "Passwort bestätigen",
        firstName: "Vorname",
        lastName: "Nachname",
        submit: "Anmelden",
        loginLink: "Bereits ein Konto?",
        loginText: "Hier anmelden",
      },
      validation: {
        required: "Dieses Feld ist erforderlich",
        emailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
        passwordMismatch: "Passwörter stimmen nicht überein",
        passwordMinLength: "Passwort muss mindestens 6 Zeichen lang sein",
        usernameMinLength: "Benutzername muss mindestens 3 Zeichen lang sein",
      },
      success: {
        title: "Willkommen an Bord!",
        message:
          "Ihr Konto wurde erfolgreich erstellt. Sie sind jetzt ein gleichberechtigter Aktionär in unserem kollektiven Unternehmen.",
      },
      error: {
        title: "Anmeldung fehlgeschlagen",
        userExists:
          "Ein Benutzer mit dieser E-Mail oder diesem Benutzernamen existiert bereits",
        serverError:
          "Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.",
      },
    },
    forum: {
      title: "Ubuntu-Project Forum",
      subtitle: "Verbinden, Lernen und Teilen mit der Ubuntu Community",
      searchPlaceholder: "Diskussionen durchsuchen...",
      tabs: {
        recent: "Neueste",
        hot: "Beliebt",
        pinned: "Angepinnt",
      },
      categories: {
        title: "Kategorien",
      },
      stats: {
        title: "Community Statistiken",
        members: "Mitglieder",
        posts: "Beiträge",
        online: "Jetzt online",
      },
      createPost: "Neuen Beitrag erstellen",
    },
    auth: {
      loading: "Laden...",
      loginRequired: {
        title: "Anmeldung erforderlich",
        message: "Sie müssen angemeldet sein, um auf diese Seite zuzugreifen.",
        signup: "Registrieren",
        home: "Anmelden",
      },
    },
  },
};

export const getTranslations = (language: string = "en"): Translations => {
  return translations[language] || translations.en;
};
